[package]
name = "fuzzy-alchemist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-derived = "0.8.2"
rand = "0.8.5"
